// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrR95qDZ7jJd4NXaLCMMwGmTxzNL0V00',
    appId: '1:720561950449:web:f13d4e01ef27ac1e666350',
    messagingSenderId: '720561950449',
    projectId: 'chat-app-4a12d',
    authDomain: 'chat-app-4a12d.firebaseapp.com',
    storageBucket: 'chat-app-4a12d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuH_nPTeVpsG5R4pFceBIECFsDw6WfwIE',
    appId: '1:720561950449:android:d7eac7785182e860666350',
    messagingSenderId: '720561950449',
    projectId: 'chat-app-4a12d',
    storageBucket: 'chat-app-4a12d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPEsy9UG_YVbg_YAH9ixI7ULWo6TGHVg',
    appId: '1:720561950449:ios:42a62acc169fa775666350',
    messagingSenderId: '720561950449',
    projectId: 'chat-app-4a12d',
    storageBucket: 'chat-app-4a12d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPEsy9UG_YVbg_YAH9ixI7ULWo6TGHVg',
    appId: '1:720561950449:ios:b032101d020c587e666350',
    messagingSenderId: '720561950449',
    projectId: 'chat-app-4a12d',
    storageBucket: 'chat-app-4a12d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
